### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by eadf** [shantanugoel/esp-mqtt-oled-smartwatch#1]
Tuan's mqtt code is very flexible and prepared to be used as a module.
So there is really no need to modify any of the mqtt source files.
You can create a folder named _mqtt_ at the root of your project and put the entire esp_mqtt project in there (if your're used to git submodules or subtrees you can use those)

This way you can keep your mqtt code up to date with changes in esp_mqtt.

You will have to add `mqtt/mqtt mqtt/modules` to your `MODULES` variable in the Makefile.

Here is an example: https://github.com/eadf/esp_mqtt_lcd
It's an project where i import an always up to date version of esp_mqtt as a module with git subtree.

**Comment by shantanugoel** [comment]
Thanks for the suggestion :) I'll try this out.
